fix: Rubocop offense in custom code
After upgrading to 2.5.1 this lines a breaking the Github Actions Rubocop build.

```
Run bundle exec rubocop --fail-level convention --display-only-fail-level-offenses -f github
  bundle exec rubocop --fail-level convention --display-only-fail-level-offenses -f github
  shell: /usr/bin/bash -e {0}

Error: Layout/LineLength: Line is too long. [216/110] (https://rubystyle.guide#max-line-length)
Error: Layout/LineLength: Line is too long. [217/110] (https://rubystyle.guide#max-line-length)
Error: Process completed with exit code 1.
```